[2025-01-19 18:15:12,600: INFO: main: Welcome to my custom log]
[2025-01-19 18:17:32,637: INFO: main: Welcome to my custom log]
[2025-01-19 19:43:45,390: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-01-19 19:43:45,412: INFO: common: yaml file: params.yaml loaded successfully]
[2025-01-19 19:43:45,415: INFO: common: created directory at: artifacts]
[2025-01-19 19:43:45,419: INFO: common: created directory at: artifacts/data_ingestion]
[2025-01-19 19:43:45,424: INFO: 986331348: Downloading data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-01-19 19:44:16,694: INFO: 986331348: Downloaded data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-01-19 20:21:34,692: INFO: main: >>>>>> stage DATA INGESTION STAGE started <<<<<<]
[2025-01-19 20:21:34,694: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-01-19 20:21:34,695: INFO: common: yaml file: params.yaml loaded successfully]
[2025-01-19 20:21:34,696: INFO: common: created directory at: artifacts]
[2025-01-19 20:21:34,697: INFO: common: created directory at: artifacts/data_ingestion]
[2025-01-19 20:21:34,698: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-01-19 20:22:16,112: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-01-19 20:22:19,210: INFO: main: >>>>>> stage DATA INGESTION STAGE completed <<<<<<

x==========x]
[2025-01-19 21:21:07,285: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-01-19 21:21:07,310: INFO: common: yaml file: params.yaml loaded successfully]
[2025-01-19 21:21:07,316: INFO: common: created directory at: artifacts]
[2025-01-19 21:21:07,322: INFO: common: created directory at: artifacts/prepare_base_model]
[2025-01-19 21:21:52,994: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-01-19 21:41:06,056: INFO: main: >>>>>> stage DATA INGESTION STAGE started <<<<<<]
[2025-01-19 21:41:06,061: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-01-19 21:41:06,064: INFO: common: yaml file: params.yaml loaded successfully]
[2025-01-19 21:41:06,064: INFO: common: created directory at: artifacts]
[2025-01-19 21:41:06,067: INFO: common: created directory at: artifacts/data_ingestion]
[2025-01-19 21:41:06,068: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-01-19 21:41:39,558: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-01-19 21:41:41,190: INFO: main: >>>>>> stage DATA INGESTION STAGE completed <<<<<<

x==========x]
[2025-01-19 21:41:41,191: INFO: main: *******************]
[2025-01-19 21:41:41,192: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2025-01-19 21:41:41,198: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-01-19 21:41:41,207: INFO: common: yaml file: params.yaml loaded successfully]
[2025-01-19 21:41:41,208: INFO: common: created directory at: artifacts]
[2025-01-19 21:41:41,208: INFO: common: created directory at: artifacts/prepare_base_model]
[2025-01-19 21:41:42,727: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-01-19 21:41:43,810: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2025-01-19 22:25:55,487: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-01-19 22:25:55,496: INFO: common: yaml file: params.yaml loaded successfully]
[2025-01-19 22:25:55,500: INFO: common: created directory at: artifacts]
[2025-01-19 22:25:55,505: INFO: common: created directory at: artifacts\training]
[2025-01-20 13:33:50,998: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-01-20 13:33:51,015: INFO: common: yaml file: params.yaml loaded successfully]
[2025-01-20 13:33:51,020: INFO: common: created directory at: artifacts]
[2025-01-20 13:33:51,020: INFO: common: created directory at: artifacts/prepare_base_model]
[2025-01-20 13:33:52,048: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-01-20 13:34:21,391: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-01-20 13:34:21,399: INFO: common: yaml file: params.yaml loaded successfully]
[2025-01-20 13:34:21,399: INFO: common: created directory at: artifacts]
[2025-01-20 13:34:21,407: INFO: common: created directory at: artifacts\training]
[2025-01-20 16:19:19,687: INFO: main: >>>>>> stage DATA INGESTION STAGE started <<<<<<]
[2025-01-20 16:19:19,702: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-01-20 16:19:19,702: INFO: common: yaml file: params.yaml loaded successfully]
[2025-01-20 16:19:19,702: INFO: common: created directory at: artifacts]
[2025-01-20 16:19:19,702: INFO: common: created directory at: artifacts/data_ingestion]
[2025-01-20 16:19:19,702: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-01-20 16:23:39,509: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-01-20 16:23:40,659: INFO: main: >>>>>> stage DATA INGESTION STAGE completed <<<<<<

x==========x]
[2025-01-20 16:23:40,660: INFO: main: *******************]
[2025-01-20 16:23:40,661: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2025-01-20 16:23:40,667: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-01-20 16:23:40,673: INFO: common: yaml file: params.yaml loaded successfully]
[2025-01-20 16:23:40,674: INFO: common: created directory at: artifacts]
[2025-01-20 16:23:40,675: INFO: common: created directory at: artifacts/prepare_base_model]
[2025-01-20 16:23:41,539: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-01-20 16:23:41,874: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2025-01-20 16:23:41,874: INFO: main: *******************]
[2025-01-20 16:23:41,874: INFO: main: >>>>>> stage Training started <<<<<<]
[2025-01-20 16:23:41,874: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-01-20 16:23:41,874: INFO: common: yaml file: params.yaml loaded successfully]
[2025-01-20 16:23:41,874: INFO: common: created directory at: artifacts]
[2025-01-20 16:23:41,874: INFO: common: created directory at: artifacts\training]
[2025-01-20 18:05:32,300: INFO: main: >>>>>> stage Training completed <<<<<<

x==========x]
[2025-01-20 20:36:00,683: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-01-20 20:36:01,027: INFO: common: yaml file: params.yaml loaded successfully]
[2025-01-20 20:36:01,034: INFO: common: created directory at: artifacts]
[2025-01-20 20:37:00,588: INFO: common: json file saved at: scores.json]
[2025-01-20 20:37:05,987: WARNING: save: Found untraced functions such as _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op while saving (showing 5 of 14). These functions will not be directly callable after loading.]
[2025-01-20 20:37:07,341: INFO: builder_impl: Assets written to: C:\Users\ADMINI~1\AppData\Local\Temp\tmpbkruu_xv\model\data\model\assets]
[2025-01-21 13:41:09,353: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-01-21 13:41:09,386: INFO: common: yaml file: params.yaml loaded successfully]
[2025-01-21 13:41:09,388: INFO: common: created directory at: artifacts]
[2025-01-21 13:42:09,265: INFO: common: json file saved at: scores.json]
[2025-01-21 13:42:14,666: WARNING: save: Found untraced functions such as _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op while saving (showing 5 of 14). These functions will not be directly callable after loading.]
[2025-01-21 13:42:15,879: INFO: builder_impl: Assets written to: C:\Users\ADMINI~1\AppData\Local\Temp\tmp07euqbd4\model\data\model\assets]
[2025-01-21 13:51:33,237: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-01-21 13:51:33,249: INFO: common: yaml file: params.yaml loaded successfully]
[2025-01-21 13:51:33,252: INFO: common: created directory at: artifacts]
[2025-01-21 13:52:36,666: INFO: common: json file saved at: scores.json]
[2025-01-21 13:52:42,164: WARNING: save: Found untraced functions such as _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op while saving (showing 5 of 14). These functions will not be directly callable after loading.]
[2025-01-21 13:52:43,820: INFO: builder_impl: Assets written to: C:\Users\ADMINI~1\AppData\Local\Temp\tmpzcb1ds75\model\data\model\assets]
[2025-01-21 13:56:44,803: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-01-21 13:56:44,814: INFO: common: yaml file: params.yaml loaded successfully]
[2025-01-21 13:56:44,817: INFO: common: created directory at: artifacts]
[2025-01-21 13:57:53,539: INFO: common: json file saved at: scores.json]
[2025-01-21 13:57:58,909: WARNING: save: Found untraced functions such as _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op while saving (showing 5 of 14). These functions will not be directly callable after loading.]
[2025-01-21 13:58:00,611: INFO: builder_impl: Assets written to: C:\Users\ADMINI~1\AppData\Local\Temp\tmp74o5g3t6\model\data\model\assets]
[2025-01-21 15:25:47,329: INFO: main: >>>>>> stage DATA INGESTION STAGE started <<<<<<]
[2025-01-21 15:25:47,333: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-01-21 15:25:47,349: INFO: common: yaml file: params.yaml loaded successfully]
[2025-01-21 15:25:47,349: INFO: common: created directory at: artifacts]
[2025-01-21 15:25:47,350: INFO: common: created directory at: artifacts/data_ingestion]
[2025-01-21 15:25:47,351: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-01-21 15:28:15,811: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-01-21 15:28:17,861: INFO: main: >>>>>> stage DATA INGESTION STAGE completed <<<<<<

x==========x]
[2025-01-21 15:28:17,861: INFO: main: *******************]
[2025-01-21 15:28:17,862: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2025-01-21 15:28:17,871: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-01-21 15:28:17,877: INFO: common: yaml file: params.yaml loaded successfully]
[2025-01-21 15:28:17,877: INFO: common: created directory at: artifacts]
[2025-01-21 15:28:17,878: INFO: common: created directory at: artifacts/prepare_base_model]
[2025-01-21 15:28:20,219: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-01-21 15:28:20,770: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2025-01-21 15:28:20,771: INFO: main: *******************]
[2025-01-21 15:28:20,772: INFO: main: >>>>>> stage Training started <<<<<<]
[2025-01-21 15:28:20,776: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-01-21 15:28:20,778: INFO: common: yaml file: params.yaml loaded successfully]
[2025-01-21 15:28:20,783: INFO: common: created directory at: artifacts]
[2025-01-21 15:28:20,785: INFO: common: created directory at: artifacts\training]
[2025-01-21 17:15:36,449: INFO: main: >>>>>> stage Training completed <<<<<<

x==========x]
[2025-01-21 17:15:36,451: INFO: main: *******************]
[2025-01-21 17:15:36,452: INFO: main: >>>>>> stage Evaluation stage started <<<<<<]
[2025-01-21 17:15:36,462: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-01-21 17:15:36,467: INFO: common: yaml file: params.yaml loaded successfully]
[2025-01-21 17:15:36,469: INFO: common: created directory at: artifacts]
[2025-01-21 17:16:35,906: INFO: common: json file saved at: scores.json]
[2025-01-21 17:16:35,907: INFO: common: json file saved at: scores.json]
[2025-01-21 17:16:41,506: WARNING: save: Found untraced functions such as _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op while saving (showing 5 of 14). These functions will not be directly callable after loading.]
[2025-01-21 17:16:45,700: INFO: builder_impl: Assets written to: C:\Users\ADMINI~1\AppData\Local\Temp\tmp5js8yk79\model\data\model\assets]
[2025-01-21 17:17:10,838: ERROR: main: No module named 'distutils._modified']
Traceback (most recent call last):
  File "main.py", line 50, in <module>
    model_evalution.main()
  File "d:\kidney-disease-classification\src\cnnClassifier\pipeline\stage_04_model_evaluation.py", line 20, in main
    evaluation.log_into_mlflow()
  File "d:\kidney-disease-classification\src\cnnClassifier\components\model_evaluation_mlflow.py", line 68, in log_into_mlflow
    mlflow.keras.log_model(self.model, "model")
  File "C:\Users\Administrator\anaconda3\envs\kidney\lib\site-packages\mlflow\tensorflow\__init__.py", line 222, in log_model
    return Model.log(
  File "C:\Users\Administrator\anaconda3\envs\kidney\lib\site-packages\mlflow\models\model.py", line 552, in log
    mlflow.tracking.fluent.log_artifacts(local_path, mlflow_model.artifact_path)
  File "C:\Users\Administrator\anaconda3\envs\kidney\lib\site-packages\mlflow\tracking\fluent.py", line 817, in log_artifacts
    MlflowClient().log_artifacts(run_id, local_dir, artifact_path)
  File "C:\Users\Administrator\anaconda3\envs\kidney\lib\site-packages\mlflow\tracking\client.py", line 1069, in log_artifacts
    self._tracking_client.log_artifacts(run_id, local_dir, artifact_path)
  File "C:\Users\Administrator\anaconda3\envs\kidney\lib\site-packages\mlflow\tracking\_tracking_service\client.py", line 448, in log_artifacts
    self._get_artifact_repo(run_id).log_artifacts(local_dir, artifact_path)
  File "C:\Users\Administrator\anaconda3\envs\kidney\lib\site-packages\mlflow\store\artifact\local_artifact_repo.py", line 58, in log_artifacts
    dir_util.copy_tree(src=local_dir, dst=artifact_dir, preserve_mode=0, preserve_times=0)
  File "C:\Users\Administrator\anaconda3\envs\kidney\lib\site-packages\setuptools\_distutils\dir_util.py", line 155, in copy_tree
    return list(itertools.chain.from_iterable(map(copy_one, names)))
  File "C:\Users\Administrator\anaconda3\envs\kidney\lib\site-packages\setuptools\_distutils\dir_util.py", line 197, in _copy_one
    file_util.copy_file(
  File "C:\Users\Administrator\anaconda3\envs\kidney\lib\site-packages\setuptools\_distutils\file_util.py", line 104, in copy_file
    from distutils._modified import newer
ModuleNotFoundError: No module named 'distutils._modified'
[2025-01-21 17:40:40,034: INFO: main: >>>>>> stage DATA INGESTION STAGE started <<<<<<]
[2025-01-21 17:40:40,037: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-01-21 17:40:40,041: INFO: common: yaml file: params.yaml loaded successfully]
[2025-01-21 17:40:40,042: INFO: common: created directory at: artifacts]
[2025-01-21 17:40:40,043: INFO: common: created directory at: artifacts/data_ingestion]
[2025-01-21 17:40:40,043: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-01-21 17:41:33,190: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-01-21 17:41:34,721: INFO: main: >>>>>> stage DATA INGESTION STAGE completed <<<<<<

x==========x]
[2025-01-21 17:41:34,725: INFO: main: *******************]
[2025-01-21 17:41:34,725: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2025-01-21 17:41:34,735: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-01-21 17:41:34,741: INFO: common: yaml file: params.yaml loaded successfully]
[2025-01-21 17:41:34,741: INFO: common: created directory at: artifacts]
[2025-01-21 17:41:34,742: INFO: common: created directory at: artifacts/prepare_base_model]
[2025-01-21 17:41:35,716: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-01-21 17:41:36,068: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2025-01-21 17:41:36,068: INFO: main: *******************]
[2025-01-21 17:41:36,069: INFO: main: >>>>>> stage Training started <<<<<<]
[2025-01-21 17:41:36,072: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-01-21 17:41:36,074: INFO: common: yaml file: params.yaml loaded successfully]
[2025-01-21 17:41:36,075: INFO: common: created directory at: artifacts]
[2025-01-21 17:41:36,075: INFO: common: created directory at: artifacts\training]
[2025-01-21 17:47:58,141: INFO: main: >>>>>> stage Training completed <<<<<<

x==========x]
[2025-01-21 17:47:58,142: INFO: main: *******************]
[2025-01-21 17:47:58,143: INFO: main: >>>>>> stage Evaluation stage started <<<<<<]
[2025-01-21 17:47:58,150: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-01-21 17:47:58,155: INFO: common: yaml file: params.yaml loaded successfully]
[2025-01-21 17:47:58,156: INFO: common: created directory at: artifacts]
[2025-01-21 17:48:50,524: INFO: common: json file saved at: scores.json]
[2025-01-21 17:48:50,525: INFO: common: json file saved at: scores.json]
[2025-01-21 17:48:52,723: WARNING: save: Found untraced functions such as _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op while saving (showing 5 of 14). These functions will not be directly callable after loading.]
[2025-01-21 17:48:54,143: INFO: builder_impl: Assets written to: C:\Users\ADMINI~1\AppData\Local\Temp\tmpgzc92t_c\model\data\model\assets]
[2025-01-21 17:49:09,781: ERROR: main: No module named 'distutils._modified']
Traceback (most recent call last):
  File "main.py", line 50, in <module>
    model_evalution.main()
  File "d:\kidney-disease-classification\src\cnnClassifier\pipeline\stage_04_model_evaluation.py", line 20, in main
    evaluation.log_into_mlflow()
  File "d:\kidney-disease-classification\src\cnnClassifier\components\model_evaluation_mlflow.py", line 68, in log_into_mlflow
    mlflow.keras.log_model(self.model, "model")
  File "C:\Users\Administrator\anaconda3\envs\kidney\lib\site-packages\mlflow\tensorflow\__init__.py", line 222, in log_model
    return Model.log(
  File "C:\Users\Administrator\anaconda3\envs\kidney\lib\site-packages\mlflow\models\model.py", line 552, in log
    mlflow.tracking.fluent.log_artifacts(local_path, mlflow_model.artifact_path)
  File "C:\Users\Administrator\anaconda3\envs\kidney\lib\site-packages\mlflow\tracking\fluent.py", line 817, in log_artifacts
    MlflowClient().log_artifacts(run_id, local_dir, artifact_path)
  File "C:\Users\Administrator\anaconda3\envs\kidney\lib\site-packages\mlflow\tracking\client.py", line 1069, in log_artifacts
    self._tracking_client.log_artifacts(run_id, local_dir, artifact_path)
  File "C:\Users\Administrator\anaconda3\envs\kidney\lib\site-packages\mlflow\tracking\_tracking_service\client.py", line 448, in log_artifacts
    self._get_artifact_repo(run_id).log_artifacts(local_dir, artifact_path)
  File "C:\Users\Administrator\anaconda3\envs\kidney\lib\site-packages\mlflow\store\artifact\local_artifact_repo.py", line 58, in log_artifacts
    dir_util.copy_tree(src=local_dir, dst=artifact_dir, preserve_mode=0, preserve_times=0)
  File "C:\Users\Administrator\anaconda3\envs\kidney\lib\site-packages\setuptools\_distutils\dir_util.py", line 155, in copy_tree
    return list(itertools.chain.from_iterable(map(copy_one, names)))
  File "C:\Users\Administrator\anaconda3\envs\kidney\lib\site-packages\setuptools\_distutils\dir_util.py", line 197, in _copy_one
    file_util.copy_file(
  File "C:\Users\Administrator\anaconda3\envs\kidney\lib\site-packages\setuptools\_distutils\file_util.py", line 104, in copy_file
    from distutils._modified import newer
ModuleNotFoundError: No module named 'distutils._modified'
[2025-01-21 17:53:20,544: INFO: main: >>>>>> stage DATA INGESTION STAGE started <<<<<<]
[2025-01-21 17:53:20,549: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-01-21 17:53:20,554: INFO: common: yaml file: params.yaml loaded successfully]
[2025-01-21 17:53:20,555: INFO: common: created directory at: artifacts]
[2025-01-21 17:53:20,556: INFO: common: created directory at: artifacts/data_ingestion]
[2025-01-21 17:53:20,556: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-01-21 17:54:19,805: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-01-21 17:54:20,590: INFO: main: >>>>>> stage DATA INGESTION STAGE completed <<<<<<

x==========x]
[2025-01-21 17:54:20,591: INFO: main: *******************]
[2025-01-21 17:54:20,591: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2025-01-21 17:54:20,594: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-01-21 17:54:20,596: INFO: common: yaml file: params.yaml loaded successfully]
[2025-01-21 17:54:20,597: INFO: common: created directory at: artifacts]
[2025-01-21 17:54:20,597: INFO: common: created directory at: artifacts/prepare_base_model]
[2025-01-21 17:54:21,459: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-01-21 17:54:22,172: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2025-01-21 17:54:22,173: INFO: main: *******************]
[2025-01-21 17:54:22,173: INFO: main: >>>>>> stage Training started <<<<<<]
[2025-01-21 17:54:22,176: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-01-21 17:54:22,179: INFO: common: yaml file: params.yaml loaded successfully]
[2025-01-21 17:54:22,179: INFO: common: created directory at: artifacts]
[2025-01-21 17:54:22,179: INFO: common: created directory at: artifacts\training]
[2025-01-21 17:57:06,188: INFO: main: >>>>>> stage Training completed <<<<<<

x==========x]
[2025-01-21 17:57:06,189: INFO: main: *******************]
[2025-01-21 17:57:06,189: INFO: main: >>>>>> stage Evaluation stage started <<<<<<]
[2025-01-21 17:57:06,192: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-01-21 17:57:06,196: INFO: common: yaml file: params.yaml loaded successfully]
[2025-01-21 17:57:06,197: INFO: common: created directory at: artifacts]
[2025-01-21 17:57:56,114: INFO: common: json file saved at: scores.json]
[2025-01-21 17:57:56,114: INFO: common: json file saved at: scores.json]
[2025-01-21 17:57:58,433: WARNING: save: Found untraced functions such as _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op while saving (showing 5 of 14). These functions will not be directly callable after loading.]
[2025-01-21 17:57:59,449: INFO: builder_impl: Assets written to: C:\Users\ADMINI~1\AppData\Local\Temp\tmp6qis3z5y\model\data\model\assets]
[2025-01-21 17:58:12,524: ERROR: main: No module named 'distutils._modified']
Traceback (most recent call last):
  File "main.py", line 50, in <module>
    model_evalution.main()
  File "d:\kidney-disease-classification\src\cnnClassifier\pipeline\stage_04_model_evaluation.py", line 20, in main
    evaluation.log_into_mlflow()
  File "d:\kidney-disease-classification\src\cnnClassifier\components\model_evaluation_mlflow.py", line 68, in log_into_mlflow
    mlflow.keras.log_model(self.model, "model")
  File "C:\Users\Administrator\anaconda3\envs\kidney\lib\site-packages\mlflow\tensorflow\__init__.py", line 222, in log_model
    return Model.log(
  File "C:\Users\Administrator\anaconda3\envs\kidney\lib\site-packages\mlflow\models\model.py", line 552, in log
    mlflow.tracking.fluent.log_artifacts(local_path, mlflow_model.artifact_path)
  File "C:\Users\Administrator\anaconda3\envs\kidney\lib\site-packages\mlflow\tracking\fluent.py", line 817, in log_artifacts
    MlflowClient().log_artifacts(run_id, local_dir, artifact_path)
  File "C:\Users\Administrator\anaconda3\envs\kidney\lib\site-packages\mlflow\tracking\client.py", line 1069, in log_artifacts
    self._tracking_client.log_artifacts(run_id, local_dir, artifact_path)
  File "C:\Users\Administrator\anaconda3\envs\kidney\lib\site-packages\mlflow\tracking\_tracking_service\client.py", line 448, in log_artifacts
    self._get_artifact_repo(run_id).log_artifacts(local_dir, artifact_path)
  File "C:\Users\Administrator\anaconda3\envs\kidney\lib\site-packages\mlflow\store\artifact\local_artifact_repo.py", line 58, in log_artifacts
    dir_util.copy_tree(src=local_dir, dst=artifact_dir, preserve_mode=0, preserve_times=0)
  File "C:\Users\Administrator\anaconda3\envs\kidney\lib\site-packages\setuptools\_distutils\dir_util.py", line 155, in copy_tree
    return list(itertools.chain.from_iterable(map(copy_one, names)))
  File "C:\Users\Administrator\anaconda3\envs\kidney\lib\site-packages\setuptools\_distutils\dir_util.py", line 197, in _copy_one
    file_util.copy_file(
  File "C:\Users\Administrator\anaconda3\envs\kidney\lib\site-packages\setuptools\_distutils\file_util.py", line 104, in copy_file
    from distutils._modified import newer
ModuleNotFoundError: No module named 'distutils._modified'
[2025-01-21 18:07:11,834: INFO: main: >>>>>> stage DATA INGESTION STAGE started <<<<<<]
[2025-01-21 18:07:11,837: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-01-21 18:07:11,839: INFO: common: yaml file: params.yaml loaded successfully]
[2025-01-21 18:07:11,840: INFO: common: created directory at: artifacts]
[2025-01-21 18:07:11,841: INFO: common: created directory at: artifacts/data_ingestion]
[2025-01-21 18:07:11,841: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-01-21 18:07:45,512: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-01-21 18:07:46,262: INFO: main: >>>>>> stage DATA INGESTION STAGE completed <<<<<<

x==========x]
[2025-01-21 18:07:46,262: INFO: main: *******************]
[2025-01-21 18:07:46,262: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2025-01-21 18:07:46,262: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-01-21 18:07:46,262: INFO: common: yaml file: params.yaml loaded successfully]
[2025-01-21 18:07:46,262: INFO: common: created directory at: artifacts]
[2025-01-21 18:07:46,262: INFO: common: created directory at: artifacts/prepare_base_model]
[2025-01-21 18:07:47,176: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-01-21 18:07:48,453: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2025-01-21 18:07:48,453: INFO: main: *******************]
[2025-01-21 18:07:48,453: INFO: main: >>>>>> stage Training started <<<<<<]
[2025-01-21 18:07:48,453: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-01-21 18:07:48,468: INFO: common: yaml file: params.yaml loaded successfully]
[2025-01-21 18:07:48,468: INFO: common: created directory at: artifacts]
[2025-01-21 18:07:48,468: INFO: common: created directory at: artifacts\training]
[2025-01-21 18:10:14,192: INFO: main: >>>>>> stage Training completed <<<<<<

x==========x]
[2025-01-21 18:10:14,192: INFO: main: *******************]
[2025-01-21 18:10:14,208: INFO: main: >>>>>> stage Evaluation stage started <<<<<<]
[2025-01-21 18:10:14,208: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-01-21 18:10:14,208: INFO: common: yaml file: params.yaml loaded successfully]
[2025-01-21 18:10:14,208: INFO: common: created directory at: artifacts]
[2025-01-21 18:11:00,604: INFO: common: json file saved at: scores.json]
[2025-01-21 18:11:00,620: INFO: common: json file saved at: scores.json]
[2025-01-21 18:11:02,641: WARNING: save: Found untraced functions such as _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op while saving (showing 5 of 14). These functions will not be directly callable after loading.]
[2025-01-21 18:11:03,503: INFO: builder_impl: Assets written to: C:\Users\ADMINI~1\AppData\Local\Temp\tmpyzx1tpv5\model\data\model\assets]
[2025-01-21 18:11:15,802: ERROR: main: No module named 'distutils._modified']
Traceback (most recent call last):
  File "main.py", line 50, in <module>
    model_evalution.main()
  File "d:\kidney-disease-classification\src\cnnClassifier\pipeline\stage_04_model_evaluation.py", line 20, in main
    evaluation.log_into_mlflow()
  File "d:\kidney-disease-classification\src\cnnClassifier\components\model_evaluation_mlflow.py", line 68, in log_into_mlflow
    mlflow.keras.log_model(self.model, "model")
  File "C:\Users\Administrator\anaconda3\envs\kidney\lib\site-packages\mlflow\tensorflow\__init__.py", line 222, in log_model
    return Model.log(
  File "C:\Users\Administrator\anaconda3\envs\kidney\lib\site-packages\mlflow\models\model.py", line 552, in log
    mlflow.tracking.fluent.log_artifacts(local_path, mlflow_model.artifact_path)
  File "C:\Users\Administrator\anaconda3\envs\kidney\lib\site-packages\mlflow\tracking\fluent.py", line 817, in log_artifacts
    MlflowClient().log_artifacts(run_id, local_dir, artifact_path)
  File "C:\Users\Administrator\anaconda3\envs\kidney\lib\site-packages\mlflow\tracking\client.py", line 1069, in log_artifacts
    self._tracking_client.log_artifacts(run_id, local_dir, artifact_path)
  File "C:\Users\Administrator\anaconda3\envs\kidney\lib\site-packages\mlflow\tracking\_tracking_service\client.py", line 448, in log_artifacts
    self._get_artifact_repo(run_id).log_artifacts(local_dir, artifact_path)
  File "C:\Users\Administrator\anaconda3\envs\kidney\lib\site-packages\mlflow\store\artifact\local_artifact_repo.py", line 58, in log_artifacts
    dir_util.copy_tree(src=local_dir, dst=artifact_dir, preserve_mode=0, preserve_times=0)
  File "C:\Users\Administrator\anaconda3\envs\kidney\lib\site-packages\setuptools\_distutils\dir_util.py", line 155, in copy_tree
    return list(itertools.chain.from_iterable(map(copy_one, names)))
  File "C:\Users\Administrator\anaconda3\envs\kidney\lib\site-packages\setuptools\_distutils\dir_util.py", line 197, in _copy_one
    file_util.copy_file(
  File "C:\Users\Administrator\anaconda3\envs\kidney\lib\site-packages\setuptools\_distutils\file_util.py", line 104, in copy_file
    from distutils._modified import newer
ModuleNotFoundError: No module named 'distutils._modified'
[2025-01-21 18:17:11,114: INFO: main: >>>>>> stage DATA INGESTION STAGE started <<<<<<]
[2025-01-21 18:17:11,116: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-01-21 18:17:11,120: INFO: common: yaml file: params.yaml loaded successfully]
[2025-01-21 18:17:11,122: INFO: common: created directory at: artifacts]
[2025-01-21 18:17:11,122: INFO: common: created directory at: artifacts/data_ingestion]
[2025-01-21 18:17:11,123: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-01-21 18:17:45,862: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-01-21 18:17:46,881: INFO: main: >>>>>> stage DATA INGESTION STAGE completed <<<<<<

x==========x]
[2025-01-21 18:17:46,882: INFO: main: *******************]
[2025-01-21 18:17:46,882: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2025-01-21 18:17:46,888: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-01-21 18:17:46,891: INFO: common: yaml file: params.yaml loaded successfully]
[2025-01-21 18:17:46,891: INFO: common: created directory at: artifacts]
[2025-01-21 18:17:46,892: INFO: common: created directory at: artifacts/prepare_base_model]
[2025-01-21 18:17:47,658: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-01-21 18:17:47,930: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2025-01-21 18:17:47,931: INFO: main: *******************]
[2025-01-21 18:17:47,931: INFO: main: >>>>>> stage Training started <<<<<<]
[2025-01-21 18:17:47,934: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-01-21 18:17:47,937: INFO: common: yaml file: params.yaml loaded successfully]
[2025-01-21 18:17:47,938: INFO: common: created directory at: artifacts]
[2025-01-21 18:17:47,939: INFO: common: created directory at: artifacts\training]
[2025-01-21 18:20:24,969: INFO: main: >>>>>> stage Training completed <<<<<<

x==========x]
[2025-01-21 18:20:24,969: INFO: main: *******************]
[2025-01-21 18:20:24,970: INFO: main: >>>>>> stage Evaluation stage started <<<<<<]
[2025-01-21 18:20:24,973: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-01-21 18:20:24,976: INFO: common: yaml file: params.yaml loaded successfully]
[2025-01-21 18:20:24,977: INFO: common: created directory at: artifacts]
[2025-01-21 18:21:15,612: INFO: common: json file saved at: scores.json]
[2025-01-21 18:21:15,613: INFO: common: json file saved at: scores.json]
[2025-01-21 18:21:18,458: WARNING: save: Found untraced functions such as _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op while saving (showing 5 of 14). These functions will not be directly callable after loading.]
[2025-01-21 18:21:19,844: INFO: builder_impl: Assets written to: C:\Users\ADMINI~1\AppData\Local\Temp\tmpbsbb59tp\model\data\model\assets]
[2025-01-21 18:21:35,379: INFO: main: >>>>>> stage Evaluation stage completed <<<<<<

x==========x]
[2025-01-21 18:40:46,015: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-01-21 18:40:46,079: INFO: common: yaml file: params.yaml loaded successfully]
[2025-01-21 18:40:46,081: INFO: common: created directory at: artifacts]
[2025-01-21 18:42:02,942: INFO: common: json file saved at: scores.json]
[2025-01-21 18:42:57,056: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-01-21 18:42:57,062: INFO: common: yaml file: params.yaml loaded successfully]
[2025-01-21 18:42:57,062: INFO: common: created directory at: artifacts]
[2025-01-21 18:44:15,573: INFO: common: json file saved at: scores.json]
[2025-01-21 18:47:53,037: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-01-21 18:47:53,045: INFO: common: yaml file: params.yaml loaded successfully]
[2025-01-21 18:47:53,053: INFO: common: created directory at: artifacts]
[2025-01-21 18:48:43,702: INFO: common: json file saved at: scores.json]
[2025-01-21 18:48:48,317: WARNING: save: Found untraced functions such as _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op while saving (showing 5 of 14). These functions will not be directly callable after loading.]
[2025-01-21 18:48:49,460: INFO: builder_impl: Assets written to: C:\Users\ADMINI~1\AppData\Local\Temp\tmp0smdwa9v\model\data\model\assets]
[2025-01-21 19:00:28,589: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-01-21 19:00:28,605: INFO: common: yaml file: params.yaml loaded successfully]
[2025-01-21 19:00:28,613: INFO: common: created directory at: artifacts]
[2025-01-21 19:01:23,316: INFO: common: json file saved at: scores.json]
[2025-01-21 19:01:27,509: WARNING: save: Found untraced functions such as _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op while saving (showing 5 of 14). These functions will not be directly callable after loading.]
[2025-01-21 19:01:28,669: INFO: builder_impl: Assets written to: C:\Users\ADMINI~1\AppData\Local\Temp\tmps8by7unl\model\data\model\assets]
[2025-01-21 19:03:58,099: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-01-21 19:03:58,107: INFO: common: yaml file: params.yaml loaded successfully]
[2025-01-21 19:03:58,115: INFO: common: created directory at: artifacts]
[2025-01-21 19:04:51,521: INFO: common: json file saved at: scores.json]
[2025-01-21 19:04:57,868: WARNING: save: Found untraced functions such as _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op while saving (showing 5 of 14). These functions will not be directly callable after loading.]
[2025-01-21 19:04:59,575: INFO: builder_impl: Assets written to: C:\Users\ADMINI~1\AppData\Local\Temp\tmpcmvhq1v4\model\data\model\assets]
[2025-01-21 19:07:27,078: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-01-21 19:07:27,086: INFO: common: yaml file: params.yaml loaded successfully]
[2025-01-21 19:07:27,094: INFO: common: created directory at: artifacts]
[2025-01-21 19:08:25,622: INFO: common: json file saved at: scores.json]
[2025-01-21 19:08:31,508: WARNING: save: Found untraced functions such as _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op while saving (showing 5 of 14). These functions will not be directly callable after loading.]
[2025-01-21 19:08:33,383: INFO: builder_impl: Assets written to: C:\Users\ADMINI~1\AppData\Local\Temp\tmppl14uuxv\model\data\model\assets]
[2025-01-21 20:37:05,992: INFO: stage_01_data_ingestion: >>>>>> stage Data Ingestion Stage started <<<<<<]
[2025-01-21 20:37:05,992: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-01-21 20:37:06,000: INFO: common: yaml file: params.yaml loaded successfully]
[2025-01-21 20:37:06,000: INFO: common: created directory at: artifacts]
[2025-01-21 20:37:06,000: INFO: common: created directory at: artifacts/data_ingestion]
[2025-01-21 20:37:06,000: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-01-21 20:37:41,577: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-01-21 20:37:42,952: INFO: stage_01_data_ingestion: >>>>>> stage Data Ingestion Stage completed <<<<<<

x==========x]
[2025-01-21 20:38:00,963: INFO: stage_02_prepare_base_model: *******************]
[2025-01-21 20:38:00,963: INFO: stage_02_prepare_base_model: >>>>>> stage Prepare base model started <<<<<<]
[2025-01-21 20:38:00,963: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-01-21 20:38:00,963: INFO: common: yaml file: params.yaml loaded successfully]
[2025-01-21 20:38:00,971: INFO: common: created directory at: artifacts]
[2025-01-21 20:38:00,971: INFO: common: created directory at: artifacts/prepare_base_model]
[2025-01-21 20:38:01,702: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-01-21 20:38:02,018: INFO: stage_02_prepare_base_model: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2025-01-21 20:38:13,122: INFO: stage_03_model_training: *******************]
[2025-01-21 20:38:13,122: INFO: stage_03_model_training: >>>>>> stage Training started <<<<<<]
[2025-01-21 20:38:13,122: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-01-21 20:38:13,122: INFO: common: yaml file: params.yaml loaded successfully]
[2025-01-21 20:38:13,122: INFO: common: created directory at: artifacts]
[2025-01-21 20:38:13,130: INFO: common: created directory at: artifacts\training]
[2025-01-21 22:00:30,026: INFO: stage_03_model_training: >>>>>> stage Training completed <<<<<<

x==========x]
[2025-01-21 22:00:41,136: INFO: stage_04_model_evaluation: *******************]
[2025-01-21 22:00:41,136: INFO: stage_04_model_evaluation: >>>>>> stage Evaluation stage started <<<<<<]
[2025-01-21 22:00:41,138: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-01-21 22:00:41,138: INFO: common: yaml file: params.yaml loaded successfully]
[2025-01-21 22:00:41,138: INFO: common: created directory at: artifacts]
[2025-01-21 22:01:35,797: INFO: common: json file saved at: scores.json]
[2025-01-21 22:01:35,797: INFO: common: json file saved at: scores.json]
[2025-01-21 22:01:38,133: WARNING: save: Found untraced functions such as _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op while saving (showing 5 of 14). These functions will not be directly callable after loading.]
[2025-01-21 22:01:39,071: INFO: builder_impl: Assets written to: C:\Users\ADMINI~1\AppData\Local\Temp\tmp9rd__83s\model\data\model\assets]
[2025-01-21 22:01:52,646: INFO: stage_04_model_evaluation: >>>>>> stage Evaluation stage completed <<<<<<

x==========x]
[2025-01-21 22:49:20,220: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://192.168.1.26:8080]
[2025-01-21 22:49:20,220: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2025-01-21 22:50:53,847: INFO: _internal: 127.0.0.1 - - [21/Jan/2025 22:50:53] "GET / HTTP/1.1" 200 -]
[2025-01-21 22:51:06,407: ERROR: app: Exception on /predict [POST]]
Traceback (most recent call last):
  File "C:\Users\Administrator\anaconda3\envs\kidney\lib\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Administrator\anaconda3\envs\kidney\lib\site-packages\flask\app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Administrator\anaconda3\envs\kidney\lib\site-packages\flask_cors\extension.py", line 194, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Users\Administrator\anaconda3\envs\kidney\lib\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Administrator\anaconda3\envs\kidney\lib\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\Users\Administrator\anaconda3\envs\kidney\lib\site-packages\flask_cors\decorator.py", line 130, in wrapped_function
    resp = make_response(f(*args, **kwargs))
  File "app.py", line 43, in predictRoute
    result = clApp.classifier.predict()
  File "d:\kidney-disease-classification\src\cnnClassifier\pipeline\prediction.py", line 16, in predict
    model = load_model(os.path.join("model", "model.h5"))
  File "C:\Users\Administrator\anaconda3\envs\kidney\lib\site-packages\keras\saving\saving_api.py", line 212, in load_model
    return legacy_sm_saving_lib.load_model(
  File "C:\Users\Administrator\anaconda3\envs\kidney\lib\site-packages\keras\utils\traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "C:\Users\Administrator\anaconda3\envs\kidney\lib\site-packages\keras\saving\legacy\save.py", line 230, in load_model
    raise IOError(
OSError: No file or directory found at model\model.h5
[2025-01-21 22:51:06,419: INFO: _internal: 127.0.0.1 - - [21/Jan/2025 22:51:06] "[35m[1mPOST /predict HTTP/1.1[0m" 500 -]
[2025-01-21 22:51:56,880: INFO: _internal: 127.0.0.1 - - [21/Jan/2025 22:51:56] "GET / HTTP/1.1" 200 -]
[2025-01-21 22:52:18,085: ERROR: app: Exception on /predict [POST]]
Traceback (most recent call last):
  File "C:\Users\Administrator\anaconda3\envs\kidney\lib\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Administrator\anaconda3\envs\kidney\lib\site-packages\flask\app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Administrator\anaconda3\envs\kidney\lib\site-packages\flask_cors\extension.py", line 194, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Users\Administrator\anaconda3\envs\kidney\lib\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Administrator\anaconda3\envs\kidney\lib\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\Users\Administrator\anaconda3\envs\kidney\lib\site-packages\flask_cors\decorator.py", line 130, in wrapped_function
    resp = make_response(f(*args, **kwargs))
  File "app.py", line 43, in predictRoute
    result = clApp.classifier.predict()
  File "d:\kidney-disease-classification\src\cnnClassifier\pipeline\prediction.py", line 16, in predict
    model = load_model(os.path.join("model", "model.h5"))
  File "C:\Users\Administrator\anaconda3\envs\kidney\lib\site-packages\keras\saving\saving_api.py", line 212, in load_model
    return legacy_sm_saving_lib.load_model(
  File "C:\Users\Administrator\anaconda3\envs\kidney\lib\site-packages\keras\utils\traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "C:\Users\Administrator\anaconda3\envs\kidney\lib\site-packages\keras\saving\legacy\save.py", line 230, in load_model
    raise IOError(
OSError: No file or directory found at model\model.h5
[2025-01-21 22:52:18,085: INFO: _internal: 127.0.0.1 - - [21/Jan/2025 22:52:18] "[35m[1mPOST /predict HTTP/1.1[0m" 500 -]
[2025-01-21 22:54:13,485: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://192.168.1.26:8080]
[2025-01-21 22:54:13,501: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2025-01-21 22:54:19,006: INFO: _internal: 127.0.0.1 - - [21/Jan/2025 22:54:18] "GET / HTTP/1.1" 200 -]
[2025-01-21 22:54:25,844: ERROR: app: Exception on /predict [POST]]
Traceback (most recent call last):
  File "C:\Users\Administrator\anaconda3\envs\kidney\lib\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Administrator\anaconda3\envs\kidney\lib\site-packages\flask\app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Administrator\anaconda3\envs\kidney\lib\site-packages\flask_cors\extension.py", line 194, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Users\Administrator\anaconda3\envs\kidney\lib\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Administrator\anaconda3\envs\kidney\lib\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\Users\Administrator\anaconda3\envs\kidney\lib\site-packages\flask_cors\decorator.py", line 130, in wrapped_function
    resp = make_response(f(*args, **kwargs))
  File "app.py", line 43, in predictRoute
    result = clApp.classifier.predict()
  File "d:\kidney-disease-classification\src\cnnClassifier\pipeline\prediction.py", line 16, in predict
    model = load_model(os.path.join("model", "model.h5"))
  File "C:\Users\Administrator\anaconda3\envs\kidney\lib\site-packages\keras\saving\saving_api.py", line 212, in load_model
    return legacy_sm_saving_lib.load_model(
  File "C:\Users\Administrator\anaconda3\envs\kidney\lib\site-packages\keras\utils\traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "C:\Users\Administrator\anaconda3\envs\kidney\lib\site-packages\keras\saving\legacy\save.py", line 230, in load_model
    raise IOError(
OSError: No file or directory found at model\model.h5
[2025-01-21 22:54:25,854: INFO: _internal: 127.0.0.1 - - [21/Jan/2025 22:54:25] "[35m[1mPOST /predict HTTP/1.1[0m" 500 -]
